# Generated by Django 3.0.4 on 2020-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200324_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='api.Category'),
        ),
    ]
